### PR TITLE
build: use autotools

### PR DESCRIPTION
**Pull request by brgl**
I'd like to add support for this project to yocto. In order to allow for easy cross-compilation this patch proposes to use autotools instead of a handcoded Makefile as a standard way of building. All the files are still installed as before.

### CODE REVIEW

**Comment by Airblader** [comment]
Thanks for the PR, this sounds great! The Travis configuration needs to be adjusted as well, let's get it done and we can merge this. :-)

**Comment by brgl** [comment]
I don't really know travis - I've added some changes to travis.yml, but it doesn't seem to work. Could you help with this?

**Comment by Airblader** [comment]
After your changes to the Travis configuration, it now fails with undefined references to seemingly just anything related to X11 or libev, so my feeling is that this is a linking issue with the autotools setup, Travis itself runs fine now. I'm not really versed in autotools, so I cannot say much about that.

**Comment by brgl** [comment]
Strange, it builds for me locally as well as in yocto with this patch applied. I'll take a closer look then.

**Comment by brgl** [comment]
So it compiles fine and then the linkage fails: `gcc -D'__VERSION="1.6"' "-I../include" -std=gnu99 -Wall -Wundef -Wshadow -Wformat-security  -g -O2 -lev -lX11 -lXi -lXfixes  -o unclutter cursor.o event.o extensions.o unclutter.o util.o ` as if the libraries couldn't be found. Strange, the X11 libs use pkgconfig in my configure.ac.

**Pull request closed without merging**
